### PR TITLE
Cli to rpc

### PR DESCRIPTION
**Pull request by edvinnn**

### CODE REVIEW

**Comment by edvinnn** [comment]
The CLI now calls the corresponding methods in `dhtnode` via RPC from the `dhtctl`. The methods in `dhtnode` however are not yet implemented, but just returns `true` to prove the PRC functionality for now. 

I have removed the `sendPacket` function from `dhtnode` since I think it should be used in another way from the functions in `ctl`, so then we can implement it towards the Kademlia network later on. What do you think on that?

**Comment by edvinnn** [comment]
> The CLI now calls the corresponding methods in `dhtnode` via RPC from the `dhtctl`. The methods in `dhtnode` however are not yet implemented, but just returns `true` to prove the PRC functionality for now.
> 
> I have removed the `sendPacket` function from `dhtnode` since I think it should be used in another way from the functions in `ctl`, so then we can implement it towards the Kademlia network later on. What do you think on that?

Ahh... I don't know actually. I was thinking that we would call the `sendPacket` with the ID as an argument rather than the address and let the `sendPacket` do the translation between ID --> Address. We could also have another function do the translation instead... but that's just an question of design, right?

**Comment by optmzr** [comment]
> I have removed the `sendPacket` function from `dhtnode` since I think it should be used in another way from the functions in `ctl`, so then we can implement it towards the Kademlia network later on. What do you think on that?

`sendPacket` was only there to demonstrate the UDP communication between nodes, right? So it isn't related to the RPC CLI?

**Comment by edvinnn** [comment]
> > I have removed the `sendPacket` function from `dhtnode` since I think it should be used in another way from the functions in `ctl`, so then we can implement it towards the Kademlia network later on. What do you think on that?
> 
> `sendPacket` was only there to demonstrate the UDP communication between nodes, right? So it isn't related to the RPC CLI?

Correct

**Comment by optmzr** [comment]
MERGE?!

**Pull request merged**
